language: node_js
node_js:
  - "8"

before_install:
  - npm install -g bower

install:
  - npm install
  - bower install

script:
  - ./node_modules/.bin/gulp

cache:
  directories:
    - "node_modules"
    - "bower_components"
